INSERT INTO UNIT_OF_MEASURE(description) VALUES ('teaspoon');
INSERT INTO UNIT_OF_MEASURE(description) VALUES ('tablespoon');
INSERT INTO UNIT_OF_MEASURE(description) VALUES ('cup');
INSERT INTO UNIT_OF_MEASURE(description) VALUES ('pinch');
INSERT INTO UNIT_OF_MEASURE(description) VALUES ('ounce');
INSERT INTO CATEGORY(description) VALUES ('Russian');
INSERT INTO CATEGORY(description) VALUES ('Italian');
INSERT INTO CATEGORY(description) VALUES ('Mexican');
INSERT INTO CATEGORY(description) VALUES ('European');
INSERT INTO CATEGORY(description) VALUES ('Fast Food');